openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de DNS over HTTP
  description: Documentaci贸n de la API de DNS over HTTP de la materia 75.43 Introducci贸n a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicaci贸n
paths:
  /domains/{domain}:
    get:
      operationId: "api.domains.obtener_dominio"
      tags:
        - "Domains"
      summary: "Obtiene la IP asociada a un dominio en particular"
      description: "Obtiene la IP de un dominio ya sea custom o no"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El nombre del dominio
      responses:
        200:
          description: "Se obtuvo el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Dominio no encontrado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDomain'
  /custom-domains:
    post:
      operationId: "api.domains.agregar_dominio"
      tags:
        - "Domains"
      summary: "Crea un dominio custom"
      description: "Crea un nuevo dominio y lo agrega a la lista de dominios custom"
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomDomain'
      responses:
        201:
          description: "Se creo el custom domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: "Dominio duplicado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDomain'
    get:
      operationId: "api.domains.obtener_dominios"
      tags:
        - "Domains"
      summary: "Obtiene todos los dominios custom"
      description: "Obtiene todos los dominios, tambien se puede aplicar un filtro"
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Filtro para la query
      responses:
        200:
          description: "Lista con los dominios"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
  /custom-domains/{domain}:
    put:
      operationId: "api.domains.modificar_dominio"
      tags:
        - "Domains"
      summary: "Edita un dominio custom"
      description: "Edita un dominio ya existente en el sistema"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El nombre del dominio
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomDomain'
      responses:
        200:
          description: "Se modifico el custom domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Dominio no encontrado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDomain'
        400:
          description: "Body incorrecto"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDomain'
    delete:
      operationId: "api.domains.eliminar_dominio"
      tags:
        - "Domains"
      summary: "Borra un dominio custom"
      description: "Borra un dominio existente en el sistema"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El nombre del dominio
      responses:
        200:
          description: "borro el custom domain correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Dominio no encontrado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDomain'
# Declaraci贸n de tipos de datos
components:
  schemas:
    Domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    CustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
    ErrorDomain:
      type: "object"
      properties:
        error:
          type: "string"
    Items:
      type: "array"
      items:
        type: "object"
    Error:
      type: "object"
      properties:
        codigo:
          type: "number"
        mensaje:
          type: "string"
